
export const getEmojiName = (code: number): string => {
    // Emoticons (1F600-1F64F)
    if (code === 0x1F600) return "GRINNING FACE";
    if (code === 0x1F601) return "GRINNING FACE WITH SMILING EYES";
    if (code === 0x1F602) return "FACE WITH TEARS OF JOY";
    if (code === 0x1F603) return "SMILING FACE WITH OPEN MOUTH";
    if (code === 0x1F604) return "SMILING FACE WITH OPEN MOUTH AND SMILING EYES";
    if (code === 0x1F605) return "SMILING FACE WITH OPEN MOUTH AND COLD SWEAT";
    if (code === 0x1F606) return "SMILING FACE WITH OPEN MOUTH AND TIGHTLY-CLOSED EYES";
    if (code === 0x1F607) return "SMILING FACE WITH HALO";
    if (code === 0x1F608) return "SMILING FACE WITH HORNS";
    if (code === 0x1F609) return "WINKING FACE";
    if (code === 0x1F60A) return "SMILING FACE WITH SMILING EYES";
    if (code === 0x1F60B) return "FACE SAVORING DELICIOUS FOOD";
    if (code === 0x1F60C) return "RELIEVED FACE";
    if (code === 0x1F60D) return "SMILING FACE WITH HEART-SHAPED EYES";
    if (code === 0x1F60E) return "SMILING FACE WITH SUNGLASSES";
    if (code === 0x1F60F) return "SMIRKING FACE";
    if (code === 0x1F610) return "NEUTRAL FACE";
    if (code === 0x1F611) return "EXPRESSIONLESS FACE";
    if (code === 0x1F612) return "UNAMUSED FACE";
    if (code === 0x1F613) return "FACE WITH COLD SWEAT";
    if (code === 0x1F614) return "PENSIVE FACE";
    if (code === 0x1F615) return "CONFUSED FACE";
    if (code === 0x1F616) return "CONFOUNDED FACE";
    if (code === 0x1F617) return "KISSING FACE";
    if (code === 0x1F618) return "FACE THROWING A KISS";
    if (code === 0x1F619) return "KISSING FACE WITH SMILING EYES";
    if (code === 0x1F61A) return "KISSING FACE WITH CLOSED EYES";
    if (code === 0x1F61B) return "FACE WITH STUCK-OUT TONGUE";
    if (code === 0x1F61C) return "FACE WITH STUCK-OUT TONGUE AND WINKING EYE";
    if (code === 0x1F61D) return "FACE WITH STUCK-OUT TONGUE AND TIGHTLY-CLOSED EYES";
    if (code === 0x1F61E) return "DISAPPOINTED FACE";
    if (code === 0x1F61F) return "WORRIED FACE";
    if (code === 0x1F620) return "ANGRY FACE";
    if (code === 0x1F621) return "POUTING FACE";
    if (code === 0x1F622) return "CRYING FACE";
    if (code === 0x1F623) return "PERSEVERING FACE";
    if (code === 0x1F624) return "FACE WITH LOOK OF TRIUMPH";
    if (code === 0x1F625) return "DISAPPOINTED BUT RELIEVED FACE";
    if (code === 0x1F626) return "FROWNING FACE WITH OPEN MOUTH";
    if (code === 0x1F627) return "ANGUISHED FACE";
    if (code === 0x1F628) return "FEARFUL FACE";
    if (code === 0x1F629) return "WEARY FACE";
    if (code === 0x1F62A) return "SLEEPY FACE";
    if (code === 0x1F62B) return "TIRED FACE";
    if (code === 0x1F62C) return "GRIMACING FACE";
    if (code === 0x1F62D) return "LOUDLY CRYING FACE";
    if (code === 0x1F62E) return "FACE WITH OPEN MOUTH";
    if (code === 0x1F62F) return "HUSHED FACE";
    if (code === 0x1F630) return "FACE WITH OPEN MOUTH AND COLD SWEAT";
    if (code === 0x1F631) return "FACE SCREAMING IN FEAR";
    if (code === 0x1F632) return "ASTONISHED FACE";
    if (code === 0x1F633) return "FLUSHED FACE";
    if (code === 0x1F634) return "SLEEPING FACE";
    if (code === 0x1F635) return "DIZZY FACE";
    if (code === 0x1F636) return "FACE WITHOUT MOUTH";
    if (code === 0x1F637) return "FACE WITH MEDICAL MASK";
    if (code === 0x1F638) return "GRINNING CAT FACE WITH SMILING EYES";
    if (code === 0x1F639) return "CAT FACE WITH TEARS OF JOY";
    if (code === 0x1F63A) return "SMILING CAT FACE WITH OPEN MOUTH";
    if (code === 0x1F63B) return "SMILING CAT FACE WITH HEART-SHAPED EYES";
    if (code === 0x1F63C) return "CAT FACE WITH WRY SMILE";
    if (code === 0x1F63D) return "KISSING CAT FACE WITH CLOSED EYES";
    if (code === 0x1F63E) return "POUTING CAT FACE";
    if (code === 0x1F63F) return "CRYING CAT FACE";
    if (code === 0x1F640) return "WEARY CAT FACE";
    if (code === 0x1F641) return "SLIGHTLY FROWNING FACE";
    if (code === 0x1F642) return "SLIGHTLY SMILING FACE";
    if (code === 0x1F643) return "UPSIDE-DOWN FACE";
    if (code === 0x1F644) return "FACE WITH ROLLING EYES";
    if (code === 0x1F645) return "FACE WITH NO GOOD GESTURE";
    if (code === 0x1F646) return "FACE WITH OK GESTURE";
    if (code === 0x1F647) return "PERSON BOWING DEEPLY";
    if (code === 0x1F648) return "SEE-NO-EVIL MONKEY";
    if (code === 0x1F649) return "HEAR-NO-EVIL MONKEY";
    if (code === 0x1F64A) return "SPEAK-NO-EVIL MONKEY";
    if (code === 0x1F64B) return "HAPPY PERSON RAISING ONE HAND";
    if (code === 0x1F64C) return "PERSON RAISING BOTH HANDS IN CELEBRATION";
    if (code === 0x1F64D) return "PERSON FROWNING";
    if (code === 0x1F64E) return "PERSON WITH POUTING FACE";
    if (code === 0x1F64F) return "PERSON WITH FOLDED HANDS";

    // Transport (1F680-1F6C0)
    if (code === 0x1F680) return "ROCKET";
    if (code === 0x1F681) return "HELICOPTER";
    if (code === 0x1F682) return "STEAM LOCOMOTIVE";
    if (code === 0x1F683) return "RAILWAY CAR";
    if (code === 0x1F684) return "HIGH-SPEED TRAIN";
    if (code === 0x1F685) return "HIGH-SPEED TRAIN WITH BULLET NOSE";
    if (code === 0x1F686) return "TRAIN";
    if (code === 0x1F687) return "METRO";
    if (code === 0x1F688) return "LIGHT RAIL";
    if (code === 0x1F689) return "STATION";
    if (code === 0x1F68A) return "TRAM";
    if (code === 0x1F68B) return "TRAM CAR";
    if (code === 0x1F68C) return "BUS";
    if (code === 0x1F68D) return "ONCOMING BUS";
    if (code === 0x1F68E) return "TROLLEYBUS";
    if (code === 0x1F68F) return "BUS STOP";
    if (code === 0x1F690) return "MINIBUS";
    if (code === 0x1F691) return "AMBULANCE";
    if (code === 0x1F692) return "FIRE ENGINE";
    if (code === 0x1F693) return "POLICE CAR";
    if (code === 0x1F694) return "ONCOMING POLICE CAR";
    if (code === 0x1F695) return "TAXI";
    if (code === 0x1F696) return "ONCOMING TAXI";
    if (code === 0x1F697) return "AUTOMOBILE";
    if (code === 0x1F698) return "ONCOMING AUTOMOBILE";
    if (code === 0x1F699) return "RECREATIONAL VEHICLE";
    if (code === 0x1F69A) return "DELIVERY TRUCK";
    if (code === 0x1F69B) return "ARTICULATED LORRY";
    if (code === 0x1F69C) return "TRACTOR";
    if (code === 0x1F69D) return "MONORAIL";
    if (code === 0x1F69E) return "MOUNTAIN RAILWAY";
    if (code === 0x1F69F) return "SUSPENSION RAILWAY";
    if (code === 0x1F6A0) return "MOUNTAIN CABLEWAY";
    if (code === 0x1F6A1) return "AERIAL TRAMWAY";
    if (code === 0x1F6A2) return "SHIP";
    if (code === 0x1F6A3) return "ROWBOAT";
    if (code === 0x1F6A4) return "SPEEDBOAT";
    if (code === 0x1F6A5) return "HORIZONTAL TRAFFIC LIGHT";
    if (code === 0x1F6A6) return "VERTICAL TRAFFIC LIGHT";
    if (code === 0x1F6A7) return "CONSTRUCTION SIGN";
    if (code === 0x1F6A8) return "POLICE CARS REVOLVING LIGHT";
    if (code === 0x1F6A9) return "TRIANGULAR FLAG ON POST";
    if (code === 0x1F6AA) return "DOOR";
    if (code === 0x1F6AB) return "NO ENTRY SIGN";
    if (code === 0x1F6AC) return "SMOKING SYMBOL";
    if (code === 0x1F6AD) return "NO SMOKING SYMBOL";
    if (code === 0x1F6AE) return "PUT LITTER IN ITS PLACE SYMBOL";
    if (code === 0x1F6AF) return "DO NOT LITTER SYMBOL";
    if (code === 0x1F6B0) return "POTABLE WATER SYMBOL";
    if (code === 0x1F6B1) return "NON-POTABLE WATER SYMBOL";
    if (code === 0x1F6B2) return "BICYCLE";
    if (code === 0x1F6B3) return "NO BICYCLES";
    if (code === 0x1F6B4) return "BICYCLIST";
    if (code === 0x1F6B5) return "MOUNTAIN BICYCLIST";
    if (code === 0x1F6B6) return "PEDESTRIAN";
    if (code === 0x1F6B7) return "NO PEDESTRIANS";
    if (code === 0x1F6B8) return "CHILDREN CROSSING";
    if (code === 0x1F6B9) return "MENS SYMBOL";
    if (code === 0x1F6BA) return "WOMENS SYMBOL";
    if (code === 0x1F6BB) return "RESTROOM";
    if (code === 0x1F6BC) return "BABY SYMBOL";
    if (code === 0x1F6BD) return "TOILET";
    if (code === 0x1F6BE) return "WATER CLOSET";
    if (code === 0x1F6BF) return "SHOWER";
    if (code === 0x1F6C0) return "BATH";

    // Misc (Selected common ones)
    if (code === 0x1F300) return "CYCLONE";
    if (code === 0x1F301) return "FOGGY";
    if (code === 0x1F302) return "CLOSED UMBRELLA";
    if (code === 0x1F303) return "NIGHT WITH STARS";
    if (code === 0x1F304) return "SUNRISE OVER MOUNTAINS";
    if (code === 0x1F305) return "SUNRISE";
    if (code === 0x1F306) return "CITYSCAPE AT DUSK";
    if (code === 0x1F307) return "SUNSET OVER BUILDINGS";
    if (code === 0x1F308) return "RAINBOW";
    if (code === 0x1F309) return "BRIDGE AT NIGHT";
    if (code === 0x1F30A) return "WATER WAVE";
    if (code === 0x1F30B) return "VOLCANO";
    if (code === 0x1F30C) return "MILKY WAY";
    if (code === 0x1F30D) return "EARTH GLOBE EUROPE-AFRICA";
    if (code === 0x1F30E) return "EARTH GLOBE AMERICAS";
    if (code === 0x1F30F) return "EARTH GLOBE ASIA-AUSTRALIA";
    if (code === 0x1F310) return "GLOBE WITH MERIDIANS";
    if (code === 0x1F311) return "NEW MOON SYMBOL";
    if (code === 0x1F312) return "WAXING CRESCENT MOON SYMBOL";
    if (code === 0x1F313) return "FIRST QUARTER MOON SYMBOL";
    if (code === 0x1F314) return "WAXING GIBBOUS MOON SYMBOL";
    if (code === 0x1F315) return "FULL MOON SYMBOL";
    if (code === 0x1F316) return "WANING GIBBOUS MOON SYMBOL";
    if (code === 0x1F317) return "LAST QUARTER MOON SYMBOL";
    if (code === 0x1F318) return "WANING CRESCENT MOON SYMBOL";
    if (code === 0x1F319) return "CRESCENT MOON";
    if (code === 0x1F31A) return "NEW MOON WITH FACE";
    if (code === 0x1F31B) return "FIRST QUARTER MOON WITH FACE";
    if (code === 0x1F31C) return "LAST QUARTER MOON WITH FACE";
    if (code === 0x1F31D) return "FULL MOON WITH FACE";
    if (code === 0x1F31E) return "SUN WITH FACE";
    if (code === 0x1F31F) return "GLOWING STAR";
    if (code === 0x1F320) return "SHOOTING STAR";

    if (code >= 0x1F600 && code <= 0x1F64F) return "Emoticon";
    if (code >= 0x1F680 && code <= 0x1F6FF) return "Transport Symbol";
    if (code >= 0x1F300 && code <= 0x1F5FF) return "Misc Symbol & Pictograph";
    if (code >= 0x1F900 && code <= 0x1F9FF) return "Supplemental Symbol";

    return "Emoji Character";
};
